srcdir = .

GUIX = ${srcdir}/guix.texi
GUIX_ES = ${srcdir}/guix.es.texi
GUIX_PO = ${srcdir}/guix.es.po
GUIX_POT = ${srcdir}/guix.pot
# HSUSER = ${srcdir}/hsuser.texi
# HSUSER_ES = ${srcdir}/hsuser.es.texi
# HSUSER_PO = ${srcdir}/hsuser.es.po
# HSUSER_POT = ${srcdir}/hsuser.pot
# RLUSER = ${srcdir}/rluser.texi
# RLUSER_ES = ${srcdir}/rluser.es.texi
# RLUSER_PO = ${srcdir}/rluser.es.po
# RLUSER_POT = ${srcdir}/rluser.pot

# .PHONY: actualiza_pot html info libro pdf texi

bubble-sort: 
	gcc bubble-sort.c -o bubble-sort

bubble: 
	gcc bubble.c -o bubble 

countingsort: 
	g++ countingsort.cc -o countingsort

heap:
	g++ heap.cc -o heap

quicksort:
	gcc quicksort.c -o quicksort

# jump:
# 	gcc jump.c -o jump

mergesort:
	gcc mergesort.c -o mergesort

selection-sort:
	gcc selection-sort.c -o selection-sort

clean: 
	rm -f bubble-sort bubble countingsort heap quicksort jump merge-sort selection-sort

#all: bubble-sort bubble countingsort heap quicksort mergesort selection-sort 
	
