
bubble-sort: 
	gcc bubble-sort.c -o bubble-sort

bubble: 
	gcc bubble.c -o bubble 

countingsort: 
	g++ countingsort.cc -o countingsort

heap:
	g++ heap.cc -o heap

quicksort:
	gcc quicksort.c -o quicksort

mergesort:
	g++ mergesort.cc -o mergesort

selection-sort:
	gcc selection-sort.c -o selection-sort

clean: 
	rm -f bubble-sort bubble countingsort heap quicksort jump merge-sort selection-sort

all: bubble-sort bubble countingsort heap quicksort mergesort selection-sort 
	
