
punteros: 
	gcc punteros.c -o punteros

puntero: 
	gcc puntero.c -o puntero 

celsius: 
	gcc celsius.c -o celsius

printid: 
	gcc printid.c -o printid

parentchild:
	gcc parentchild.c -o parentchild

parentchild2:
	gcc parentchild2.c -o parentchild2

chain-of-pointers:
	gcc chain-of-pointers.c -o chain-of-pointers

waitpid-example:
	gcc waitpid-example.c -o waitpid-example

calendar:
	gcc calendar.c -o calendar

pi:
	g++ pi.cc -o pi

all: punteros puntero celsius printid parentchild parentchild2 chain-of-pointers waitpid-example calendar pi

clean:
	rm -f punteros puntero celsius printid parentchild parentchild2	chain-of-pointers waitpid-example calendar pi
