
punteros: 
	gcc punteros.c -o punteros

puntero: 
	gcc puntero.c -o puntero 

celsius: 
	gcc celsius.c -o celsius

printid: 
	gcc printid.c -o printid

all: punteros puntero celsius printid

clean:
	rm -f punteros puntero celsius printid
