
punteros: 
	gcc punteros.c -o punteros

puntero: 
	gcc puntero.c -o puntero 

celsius: 
	gcc celsius.c -o celsius

printid: 
	gcc printid.c -o printid

parentchild:
	gcc parentchild.c -o parentchild

parentchild2:
	gcc parentchild2.c -o parentchild2


all: punteros puntero celsius printid parentchild parentchild2

clean:
	rm -f punteros puntero celsius printid parentchild parentchild2	
