
circular-queue: 
	g++ circular-queue.cc -o circular-queue

queue: 
	g++ queue.cc -o queue 

queue-with-stacks: 
	g++ queue-with-stacks.cc -o queue-with-stacks

stack:
	g++ stack.cc -o stack

clean: 
	rm -f circular-queue queue queue-with-stacks stack

all: circular-queue queue queue-with-stacks stack

