
accept: 
	gcc accept.c -o accept

mem: 
	gcc mem.c -o mem

perror: 
	gcc perror.c -o perror

cpuexample:
	gcc cpuexample.c -o cpuexample

all: accept mem perror cpuexample

clean:
	rm -f accept mem perror cpuexample	
