
accept: 
	gcc accept.c -o accept

mem: 
	gcc mem.c -o mem

perror: 
	gcc perror.c -o perror

cpuexample:
	gcc cpuexample.c -o cpuexample

signals:
	gcc signals.c -o signals

glibcbuffers:
	gcc glibcbuffers.c -o glibcbuffers

glibcbuffers2:
	gcc glibcbuffers2.c -o glibcbuffers2

resizingmem:
	gcc resizingmem.c -o resizingmem

all: accept mem perror cpuexample signals glibcbuffers glibcbuffers2 resizingmem

clean:
	rm -f accept mem perror cpuexample signals glibcbuffers glibcbuffers2 resizingmem	
