
date: 
	gcc date.c -o date

file: 
	gcc file.c -o file 

hosted: 
	gcc hosted.c -o hosted

line: 
	gcc line.c -o line

macro:
	gcc macro.c -o macro

time:
	gcc time.c -o time

version:
	gcc version.c -o version


all: date file hosted line macro time version

clean:
	rm -f date file hosted line macro time version
